FROM --platform=linux/amd64 skaiworldwide/agensgraph:v2.16.0-alpine3.22

# Install pgvector extension for semantic vector search
RUN apk add --no-cache build-base git clang15 llvm15 \
    && git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git /tmp/pgvector \
    && cd /tmp/pgvector \
    && make OPTFLAGS="" \
    && make install \
    && rm -rf /tmp/pgvector \
    && apk del build-base git clang15 llvm15

# Init script: enable pgvector on startup
COPY docker/initdb-vector.sh /docker-entrypoint-initdb.d/01-vector.sh
