FROM --platform=linux/amd64 skaiworldwide/agensgraph:v2.16.0-alpine3.22

# Install pgvector extension for semantic vector search
RUN apk add --no-cache build-base git clang15 llvm15 \
    && git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git /tmp/pgvector \
    && cd /tmp/pgvector \
    && make OPTFLAGS="" \
    && make install \
    && rm -rf /tmp/pgvector \
    && apk del build-base git clang15 llvm15

# Install TimescaleDB extension for time-series metrics (used by ioc-cfn-svc)
# Requires shared_preload_libraries=timescaledb at postgres startup
RUN apk add --no-cache build-base git cmake openssl-dev lz4-dev icu-dev \
    && git clone --branch 2.28.0 https://github.com/timescale/timescaledb.git /tmp/timescaledb \
    && cd /tmp/timescaledb \
    && ./bootstrap -DREGRESS_CHECKS=OFF -DTAP_CHECKS=OFF -DWARNINGS_AS_ERRORS=OFF \
    && cd build && make && make install \
    && rm -rf /tmp/timescaledb \
    && apk del build-base git cmake openssl-dev lz4-dev

# Init script: enable pgvector on startup
COPY docker/initdb-vector.sh /docker-entrypoint-initdb.d/01-vector.sh
