// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Mycelium Contributors

"use client";

import { useState } from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface JoinIntent {
  /** Agent handle (e.g. "eng-lead"). */
  agent: string;
  /** Raw intent string from coordination_join content. */
  intent: string;
}

export interface SessionOutcome {
  /** Short session ID used in links (e.g. "aeb32312"). */
  sessionId: string;
  broken: boolean;
  plan: string;
}

interface Props {
  /** All join intents collected from coordination_join messages. May include duplicates per agent (first wins). */
  intents: JoinIntent[];
  /**
   * Issue keys generated by the CognitiveEngine (from coordination_tick issue_options).
   * When provided, these form the headline — they are the structured framing of the negotiation
   * and are a much more neutral summary than any single agent's position.
   */
  issueOptions?: Record<string, string[]> | null;
  /** Per-session outcomes to show as summary chips (room-level only). */
  outcomes?: SessionOutcome[];
  /**
   * "session" — compact banner shown inside a session view above swim lanes.
   * "room"    — wider card shown at the top of the room channel view.
   */
  variant?: "session" | "room";
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Returns true if an intent is just a "Ruling acknowledged: …" restatement. */
function isAcknowledgment(intent: string): boolean {
  return /^ruling acknowledged/i.test(intent.trim());
}

/** Deduplicate by agent handle, keeping the first occurrence. */
function dedupeByAgent(intents: JoinIntent[]): JoinIntent[] {
  const seen = new Set<string>();
  return intents.filter(({ agent }) => {
    if (seen.has(agent)) return false;
    seen.add(agent);
    return true;
  });
}

/**
 * Build a headline from issue option keys.
 * Issue keys are the CognitiveEngine's structured framing of what's being decided
 * (e.g. "Friday ship", "kill switch", "checkout bug") — far more neutral than
 * any single agent's first-sentence position.
 */
function issueHeadline(issueOptions: Record<string, string[]>, maxIssues = 5): string {
  const keys = Object.keys(issueOptions);
  if (keys.length === 0) return "";
  const shown = keys.slice(0, maxIssues);
  const rest  = keys.length - shown.length;
  const joined = shown.join(" · ");
  return rest > 0 ? `${joined} · +${rest} more` : joined;
}

// ─── Component ───────────────────────────────────────────────────────────────

export function TopicSummary({ intents, issueOptions, outcomes, variant = "session" }: Props) {
  const [expanded, setExpanded] = useState(false);

  const unique = dedupeByAgent(intents);
  if (unique.length === 0) return null;

  // Prefer original positions (non-acknowledgment) for expanded detail.
  const originals = unique.filter(x => !isAcknowledgment(x.intent));
  const toExpand  = originals.length > 0 ? originals : unique;

  // Headline priority:
  //   1. Issue option keys from the CognitiveEngine — the structured, neutral framing
  //      of what's being decided (e.g. "Friday ship · kill switch · checkout bug").
  //   2. Fall back to "N positions · no issues structured yet" if ticks haven't arrived.
  const hasIssues = issueOptions && Object.keys(issueOptions).length > 0;
  const headline  = hasIssues
    ? issueHeadline(issueOptions!)
    : `${toExpand.length} position${toExpand.length === 1 ? "" : "s"} · issues not yet structured`;

  const isRoom = variant === "room";

  return (
    <div
      style={{
        borderBottom: "1px solid var(--border)",
        background: "rgba(93,212,224,0.03)",
      }}
    >
      {/* ── Collapsed header ── */}
      <button
        onClick={() => setExpanded(e => !e)}
        className="w-full text-left flex items-start gap-3 px-5 py-3"
        aria-expanded={expanded}
      >
        {/* Label chip */}
        <span
          className="caps-mono-sm mt-0.5 flex-shrink-0"
          style={{ color: "var(--accent)", letterSpacing: "0.1em" }}
        >
          {isRoom ? "DISCUSSION" : "TOPIC"}
        </span>

        {/* Headline */}
        <span
          className="flex-1 min-w-0 font-mono text-label leading-snug"
          style={{ color: expanded ? "var(--text)" : "var(--text2)" }}
        >
          {headline}
        </span>

        {/* Right cluster: agent count + outcome chips + toggle */}
        <span className="flex items-center gap-2 flex-shrink-0 ml-2">
          {/* Outcome chips — room variant only, always visible */}
          {isRoom && outcomes && outcomes.length > 0 && (
            <span className="flex items-center gap-1.5">
              {outcomes.map(o => (
                <span
                  key={o.sessionId}
                  className="caps-mono-sm px-1.5 py-0.5 rounded"
                  style={{
                    background: o.broken ? "rgba(251,191,36,0.12)" : "rgba(52,211,153,0.12)",
                    color: o.broken ? "var(--yellow)" : "var(--green)",
                  }}
                  title={o.plan || (o.broken ? "no agreement" : "consensus reached")}
                >
                  {o.broken ? "⊘" : "✓"} {o.sessionId.slice(0, 6)}
                </span>
              ))}
            </span>
          )}

          {/* Agent count */}
          <span className="caps-mono-sm" style={{ color: "var(--muted)" }}>
            {unique.length} {unique.length === 1 ? "agent" : "agents"}
          </span>

          {/* Expand toggle */}
          <span
            className="caps-mono-sm"
            style={{ color: "var(--dim)", fontSize: 11 }}
            aria-hidden
          >
            {expanded ? "−" : "+"}
          </span>
        </span>
      </button>

      {/* ── Expanded positions ── */}
      {expanded && (
        <div
          style={{ borderTop: "1px solid var(--border)" }}
        >
          {toExpand.map(({ agent, intent }) => (
            <div
              key={agent}
              className="flex items-start gap-3 px-5 py-2.5"
              style={{ borderBottom: "1px solid var(--border)" }}
            >
              {/* Agent handle */}
              <span
                className="font-mono text-label font-semibold flex-shrink-0 mt-0.5 min-w-[90px]"
                style={{ color: "var(--accent)" }}
              >
                {agent}
              </span>

              {/* Full intent text */}
              <p
                className="font-mono text-label leading-relaxed whitespace-pre-wrap break-words min-w-0 flex-1"
                style={{ color: "var(--text2)" }}
              >
                {intent}
              </p>
            </div>
          ))}

          {/* If all were acknowledgments but we're showing them, note that. */}
          {originals.length === 0 && unique.length > 0 && (
            <div className="px-5 py-2 caps-mono-sm" style={{ color: "var(--muted)" }}>
              all agents acknowledged a human ruling before joining
            </div>
          )}
        </div>
      )}
    </div>
  );
}
